#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -n "1" -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a eww state=floating follow=on
bspc rule -a utools state=floating follow=on
bspc rule -a gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# 解决android-studio 白屏问题
# bspc rule -a android-studio state=floating border=off follow=on
# wmname LG3D &

# 多显示器问题
# xrandr --output DVI-D-0 --off --output HDMI-0 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-0 --mode 1920x1080 --pos 2560x0 --rotate normal --output DP-1 --off
xrandr --output HDMI-0 --mode 2560x1440 --rate 65

feh --bg-scale ~/.config/bspwm/bgimg.jpg
# /usr/local/clash/cfw &
fcitx5 &
picom --xrender-sync --xrender-sync-fence &

~/.config/polybar/launch.sh
dunst &
eww daemon
# utools &
# xrandr --scale 1.25x1.25 &
udiskie &
